[package]
name = "aideon-chrona"
version = "0.0.0"
edition = "2024"
authors = ["Aideon Praxis Contributors"]
license = "MIT"

[dependencies]
aideon-mneme = { path = "../mneme" }
aideon-praxis = { path = "../praxis" }
log = "0.4"
