[package]
name = "aideon-chrona"
version = "0.0.0"
edition = "2024"
authors = ["Aideon Praxis Contributors"]
license = "MIT"

[dependencies]
aideon-core-data = { path = "../core_data" }
log = "0.4"
aideon-praxis = { path = "../praxis" }
